In [1]:
import os
import joblib
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from skimage import io, color, transform
from sklearn import preprocessing

In [2]:
dataset_path = "/home/zkerroumi42/ProjetIA-ZNZ/dataset"
class_labels = ["Benign_Keratosis_(BKL)", "Molluscum", "Seborrheic_Keratoses"]

In [4]:
def load_images_and_labels(folder_path):
    images = []
    labels = []
    for class_label, folder_name in enumerate(class_labels):
        class_folder = os.path.join(folder_path, folder_name)
        for filename in os.listdir(class_folder):
            image_path = os.path.join(class_folder, filename)
            image = io.imread(image_path)
            image = color.rgb2gray(image)  
            image = transform.resize(image, (64, 64))
            # Normalisation entre 0 et 1
            image = image / 255.0
            images.append(image.flatten())  
            labels.append(class_label)
    return np.array(images), np.array(labels)

In [5]:
images, labels = load_images_and_labels(dataset_path)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(images, labels, test_size=0.2, random_state=42)

In [7]:

scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
# Entraînement du modèle
svm_classifier = SVC(kernel='linear', C=1.0)
svm_classifier.fit(X_train, y_train)

SVC(kernel='linear')

In [9]:
# Save the trained SVM model 
joblib.dump(svm_classifier, 'svm_model.h5')

# Load the model 
loaded_svm_model = joblib.load('svm_model.h5')

In [10]:
# Prédictions sur le jeu de test
y_pred_svm = loaded_svm_model.predict(X_test)

# Accuracy
accuracy_svm = accuracy_score(y_test, y_pred_svm)
print(f"SVM Accuracy: {accuracy_svm}")

SVM Accuracy: 0.6616915422885572


In [11]:
# Matrice de confusion
conf_matrix = confusion_matrix(y_test, y_pred_svm)
print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[374  40  12]
 [ 42 239 133]
 [ 39 142 185]]


In [12]:
#mesures d'évaluation
print("Classification Report:")
print(classification_report(y_test, y_pred_svm))

Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.88      0.85       426
           1       0.57      0.58      0.57       414
           2       0.56      0.51      0.53       366

    accuracy                           0.66      1206
   macro avg       0.65      0.65      0.65      1206
weighted avg       0.66      0.66      0.66      1206

